// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apifactory/proto/analytics.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	apifactory/proto/analytics.proto
	apifactory/proto/authentication.proto
	apifactory/proto/authorization.proto
	apifactory/proto/logging.proto
	apifactory/proto/scripting.proto
	apifactory/proto/service.proto
	apifactory/proto/traffic_control.proto

It has these top-level messages:
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AnalyticsProvider service

type AnalyticsProviderClient interface {
}

type analyticsProviderClient struct {
	cc *grpc.ClientConn
}

func NewAnalyticsProviderClient(cc *grpc.ClientConn) AnalyticsProviderClient {
	return &analyticsProviderClient{cc}
}

// Server API for AnalyticsProvider service

type AnalyticsProviderServer interface {
}

func RegisterAnalyticsProviderServer(s *grpc.Server, srv AnalyticsProviderServer) {
	s.RegisterService(&_AnalyticsProvider_serviceDesc, srv)
}

var _AnalyticsProvider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AnalyticsProvider",
	HandlerType: (*AnalyticsProviderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "apifactory/proto/analytics.proto",
}

func init() { proto1.RegisterFile("apifactory/proto/analytics.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 78 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x48, 0x2c, 0xc8, 0x4c,
	0x4b, 0x4c, 0x2e, 0xc9, 0x2f, 0xaa, 0xd4, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0xcc, 0x4b,
	0xcc, 0xa9, 0x2c, 0xc9, 0x4c, 0x2e, 0xd6, 0x03, 0xf3, 0x85, 0x58, 0xc1, 0x94, 0x91, 0x30, 0x97,
	0xa0, 0x23, 0x4c, 0x26, 0xa0, 0x28, 0xbf, 0x2c, 0x33, 0x25, 0xb5, 0x28, 0x89, 0x0d, 0x2c, 0x67,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xdd, 0x78, 0xe7, 0x9d, 0x46, 0x00, 0x00, 0x00,
}
