// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apifactory/proto/authorization.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AuthorizationProvider service

type AuthorizationProviderClient interface {
}

type authorizationProviderClient struct {
	cc *grpc.ClientConn
}

func NewAuthorizationProviderClient(cc *grpc.ClientConn) AuthorizationProviderClient {
	return &authorizationProviderClient{cc}
}

// Server API for AuthorizationProvider service

type AuthorizationProviderServer interface {
}

func RegisterAuthorizationProviderServer(s *grpc.Server, srv AuthorizationProviderServer) {
	s.RegisterService(&_AuthorizationProvider_serviceDesc, srv)
}

var _AuthorizationProvider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AuthorizationProvider",
	HandlerType: (*AuthorizationProviderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "apifactory/proto/authorization.proto",
}

func init() { proto1.RegisterFile("apifactory/proto/authorization.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 82 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x49, 0x2c, 0xc8, 0x4c,
	0x4b, 0x4c, 0x2e, 0xc9, 0x2f, 0xaa, 0xd4, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0x2c, 0x2d,
	0xc9, 0xc8, 0x2f, 0xca, 0xac, 0x4a, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x03, 0x8b, 0x09, 0xb1, 0x82,
	0x29, 0x23, 0x71, 0x2e, 0x51, 0x47, 0x64, 0xd9, 0x80, 0xa2, 0xfc, 0xb2, 0xcc, 0x94, 0xd4, 0xa2,
	0x24, 0x36, 0xb0, 0xbc, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x9a, 0xe9, 0x46, 0x40, 0x4e, 0x00,
	0x00, 0x00,
}
