// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apifactory/proto/scripting.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ScriptingProvider service

type ScriptingProviderClient interface {
}

type scriptingProviderClient struct {
	cc *grpc.ClientConn
}

func NewScriptingProviderClient(cc *grpc.ClientConn) ScriptingProviderClient {
	return &scriptingProviderClient{cc}
}

// Server API for ScriptingProvider service

type ScriptingProviderServer interface {
}

func RegisterScriptingProviderServer(s *grpc.Server, srv ScriptingProviderServer) {
	s.RegisterService(&_ScriptingProvider_serviceDesc, srv)
}

var _ScriptingProvider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ScriptingProvider",
	HandlerType: (*ScriptingProviderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "apifactory/proto/scripting.proto",
}

func init() { proto1.RegisterFile("apifactory/proto/scripting.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 78 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x48, 0x2c, 0xc8, 0x4c,
	0x4b, 0x4c, 0x2e, 0xc9, 0x2f, 0xaa, 0xd4, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0x4e, 0x2e,
	0xca, 0x2c, 0x28, 0xc9, 0xcc, 0x4b, 0xd7, 0x03, 0xf3, 0x85, 0x58, 0xc1, 0x94, 0x91, 0x30, 0x97,
	0x60, 0x30, 0x4c, 0x26, 0xa0, 0x28, 0xbf, 0x2c, 0x33, 0x25, 0xb5, 0x28, 0x89, 0x0d, 0x2c, 0x67,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x06, 0x50, 0xd0, 0xcf, 0x46, 0x00, 0x00, 0x00,
}
