// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apifactory/proto/service.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ServiceProvider service

type ServiceProviderClient interface {
}

type serviceProviderClient struct {
	cc *grpc.ClientConn
}

func NewServiceProviderClient(cc *grpc.ClientConn) ServiceProviderClient {
	return &serviceProviderClient{cc}
}

// Server API for ServiceProvider service

type ServiceProviderServer interface {
}

func RegisterServiceProviderServer(s *grpc.Server, srv ServiceProviderServer) {
	s.RegisterService(&_ServiceProvider_serviceDesc, srv)
}

var _ServiceProvider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ServiceProvider",
	HandlerType: (*ServiceProviderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "apifactory/proto/service.proto",
}

func init() { proto1.RegisterFile("apifactory/proto/service.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 76 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4b, 0x2c, 0xc8, 0x4c,
	0x4b, 0x4c, 0x2e, 0xc9, 0x2f, 0xaa, 0xd4, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0x4e, 0x2d,
	0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x03, 0xf3, 0x84, 0x58, 0xc1, 0x94, 0x91, 0x20, 0x17, 0x7f, 0x30,
	0x44, 0x3c, 0xa0, 0x28, 0xbf, 0x2c, 0x33, 0x25, 0xb5, 0x28, 0x89, 0x0d, 0x2c, 0x63, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x84, 0xe9, 0x47, 0x57, 0x42, 0x00, 0x00, 0x00,
}
