// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apifactory/proto/traffic_control.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TrafficControlProvider service

type TrafficControlProviderClient interface {
}

type trafficControlProviderClient struct {
	cc *grpc.ClientConn
}

func NewTrafficControlProviderClient(cc *grpc.ClientConn) TrafficControlProviderClient {
	return &trafficControlProviderClient{cc}
}

// Server API for TrafficControlProvider service

type TrafficControlProviderServer interface {
}

func RegisterTrafficControlProviderServer(s *grpc.Server, srv TrafficControlProviderServer) {
	s.RegisterService(&_TrafficControlProvider_serviceDesc, srv)
}

var _TrafficControlProvider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TrafficControlProvider",
	HandlerType: (*TrafficControlProviderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "apifactory/proto/traffic_control.proto",
}

func init() { proto1.RegisterFile("apifactory/proto/traffic_control.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 87 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4b, 0x2c, 0xc8, 0x4c,
	0x4b, 0x4c, 0x2e, 0xc9, 0x2f, 0xaa, 0xd4, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0x29, 0x4a,
	0x4c, 0x4b, 0xcb, 0x4c, 0x8e, 0x4f, 0xce, 0xcf, 0x2b, 0x29, 0xca, 0xcf, 0xd1, 0x03, 0x8b, 0x0a,
	0xb1, 0x82, 0x29, 0x23, 0x09, 0x2e, 0xb1, 0x10, 0x88, 0xbc, 0x33, 0x44, 0x3a, 0xa0, 0x28, 0xbf,
	0x2c, 0x33, 0x25, 0xb5, 0x28, 0x89, 0x0d, 0xac, 0xc0, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x85,
	0x55, 0x6b, 0x2b, 0x51, 0x00, 0x00, 0x00,
}
