// Code generated by protoc-gen-go. DO NOT EDIT.
// source: analytics.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	analytics.proto
	authentication.proto
	authorization.proto
	empty.proto
	logging.proto
	platform.proto
	scripting.proto
	service.proto
	traffic_control.proto

It has these top-level messages:
	Empty
	Values
	Response
	GetRequest
	PutRequest
	PostRequest
	PatchRequest
	DeleteRequest
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AnalyticsProvider service

type AnalyticsProviderClient interface {
}

type analyticsProviderClient struct {
	cc *grpc.ClientConn
}

func NewAnalyticsProviderClient(cc *grpc.ClientConn) AnalyticsProviderClient {
	return &analyticsProviderClient{cc}
}

// Server API for AnalyticsProvider service

type AnalyticsProviderServer interface {
}

func RegisterAnalyticsProviderServer(s *grpc.Server, srv AnalyticsProviderServer) {
	s.RegisterService(&_AnalyticsProvider_serviceDesc, srv)
}

var _AnalyticsProvider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AnalyticsProvider",
	HandlerType: (*AnalyticsProviderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "analytics.proto",
}

func init() { proto1.RegisterFile("analytics.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 64 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xcc, 0x4b, 0xcc,
	0xa9, 0x2c, 0xc9, 0x4c, 0x2e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x46,
	0xc2, 0x5c, 0x82, 0x8e, 0x30, 0x99, 0x80, 0xa2, 0xfc, 0xb2, 0xcc, 0x94, 0xd4, 0xa2, 0x24, 0x36,
	0xb0, 0x9c, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x58, 0x04, 0x21, 0xd4, 0x35, 0x00, 0x00, 0x00,
}
