// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authentication.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	authentication.proto
	authorization.proto
	empty.proto
	logging.proto
	platform.proto
	scripting.proto
	service.proto
	tracing.proto
	traffic_control.proto

It has these top-level messages:
	Empty
	Values
	Response
	GetRequest
	PutRequest
	PostRequest
	PatchRequest
	DeleteRequest
	TracingEvent
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AuthenticationProvider service

type AuthenticationProviderClient interface {
}

type authenticationProviderClient struct {
	cc *grpc.ClientConn
}

func NewAuthenticationProviderClient(cc *grpc.ClientConn) AuthenticationProviderClient {
	return &authenticationProviderClient{cc}
}

// Server API for AuthenticationProvider service

type AuthenticationProviderServer interface {
}

func RegisterAuthenticationProviderServer(s *grpc.Server, srv AuthenticationProviderServer) {
	s.RegisterService(&_AuthenticationProvider_serviceDesc, srv)
}

var _AuthenticationProvider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AuthenticationProvider",
	HandlerType: (*AuthenticationProviderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "authentication.proto",
}

func init() { proto1.RegisterFile("authentication.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 70 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x2c, 0x2d, 0xc9,
	0x48, 0xcd, 0x2b, 0xc9, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x05, 0x53, 0x46, 0x12, 0x5c, 0x62, 0x8e, 0x28, 0xd2, 0x01, 0x45, 0xf9, 0x65, 0x99,
	0x29, 0xa9, 0x45, 0x49, 0x6c, 0x60, 0x05, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xae, 0x0d,
	0xe3, 0xb9, 0x3f, 0x00, 0x00, 0x00,
}
