// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logging.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for LoggingProvider service

type LoggingProviderClient interface {
}

type loggingProviderClient struct {
	cc *grpc.ClientConn
}

func NewLoggingProviderClient(cc *grpc.ClientConn) LoggingProviderClient {
	return &loggingProviderClient{cc}
}

// Server API for LoggingProvider service

type LoggingProviderServer interface {
}

func RegisterLoggingProviderServer(s *grpc.Server, srv LoggingProviderServer) {
	s.RegisterService(&_LoggingProvider_serviceDesc, srv)
}

var _LoggingProvider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.LoggingProvider",
	HandlerType: (*LoggingProviderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "logging.proto",
}

func init() { proto1.RegisterFile("logging.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 62 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0xc9, 0x4f, 0x4f,
	0xcf, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x46, 0x82, 0x5c,
	0xfc, 0x3e, 0x10, 0xf1, 0x80, 0xa2, 0xfc, 0xb2, 0xcc, 0x94, 0xd4, 0xa2, 0x24, 0x36, 0xb0, 0x8c,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x3a, 0x4f, 0x85, 0x31, 0x00, 0x00, 0x00,
}
