// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scripting.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ScriptingProvider service

type ScriptingProviderClient interface {
	Run(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type scriptingProviderClient struct {
	cc *grpc.ClientConn
}

func NewScriptingProviderClient(cc *grpc.ClientConn) ScriptingProviderClient {
	return &scriptingProviderClient{cc}
}

func (c *scriptingProviderClient) Run(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/proto.ScriptingProvider/Run", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ScriptingProvider service

type ScriptingProviderServer interface {
	Run(context.Context, *Empty) (*Empty, error)
}

func RegisterScriptingProviderServer(s *grpc.Server, srv ScriptingProviderServer) {
	s.RegisterService(&_ScriptingProvider_serviceDesc, srv)
}

func _ScriptingProvider_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptingProviderServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ScriptingProvider/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptingProviderServer).Run(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _ScriptingProvider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ScriptingProvider",
	HandlerType: (*ScriptingProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _ScriptingProvider_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scripting.proto",
}

func init() { proto1.RegisterFile("scripting.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 91 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x4e, 0x2e, 0xca,
	0x2c, 0x28, 0xc9, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52,
	0xdc, 0xa9, 0xb9, 0x05, 0x25, 0x95, 0x10, 0x31, 0x23, 0x33, 0x2e, 0xc1, 0x60, 0x98, 0xb2, 0x80,
	0xa2, 0xfc, 0xb2, 0xcc, 0x94, 0xd4, 0x22, 0x21, 0x45, 0x2e, 0xe6, 0xa0, 0xd2, 0x3c, 0x21, 0x1e,
	0x88, 0x1a, 0x3d, 0x57, 0x90, 0x7a, 0x29, 0x14, 0x5e, 0x12, 0x1b, 0x98, 0x63, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x6b, 0x09, 0x3e, 0x9a, 0x65, 0x00, 0x00, 0x00,
}
