// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/database.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/database.proto

It has these top-level messages:
	Resource
	ListRequest
	ListResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Resource_Kind int32

const (
	Resource_UNKNOWN     Resource_Kind = 0
	Resource_TABLE       Resource_Kind = 1
	Resource_VIEW        Resource_Kind = 2
	Resource_STORED_PROC Resource_Kind = 3
)

var Resource_Kind_name = map[int32]string{
	0: "UNKNOWN",
	1: "TABLE",
	2: "VIEW",
	3: "STORED_PROC",
}
var Resource_Kind_value = map[string]int32{
	"UNKNOWN":     0,
	"TABLE":       1,
	"VIEW":        2,
	"STORED_PROC": 3,
}

func (x Resource_Kind) String() string {
	return proto1.EnumName(Resource_Kind_name, int32(x))
}
func (Resource_Kind) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Resource struct {
	Name string        `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Kind Resource_Kind `protobuf:"varint,2,opt,name=kind,enum=proto.Resource_Kind" json:"kind,omitempty"`
}

func (m *Resource) Reset()                    { *m = Resource{} }
func (m *Resource) String() string            { return proto1.CompactTextString(m) }
func (*Resource) ProtoMessage()               {}
func (*Resource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Resource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Resource) GetKind() Resource_Kind {
	if m != nil {
		return m.Kind
	}
	return Resource_UNKNOWN
}

type ListRequest struct {
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto1.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ListResponse struct {
	Resources []*Resource `protobuf:"bytes,1,rep,name=resources" json:"resources,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto1.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListResponse) GetResources() []*Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

func init() {
	proto1.RegisterType((*Resource)(nil), "proto.Resource")
	proto1.RegisterType((*ListRequest)(nil), "proto.ListRequest")
	proto1.RegisterType((*ListResponse)(nil), "proto.ListResponse")
	proto1.RegisterEnum("proto.Resource_Kind", Resource_Kind_name, Resource_Kind_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Database service

type DatabaseClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type databaseClient struct {
	cc *grpc.ClientConn
}

func NewDatabaseClient(cc *grpc.ClientConn) DatabaseClient {
	return &databaseClient{cc}
}

func (c *databaseClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/proto.Database/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Database service

type DatabaseServer interface {
	List(context.Context, *ListRequest) (*ListResponse, error)
}

func RegisterDatabaseServer(s *grpc.Server, srv DatabaseServer) {
	s.RegisterService(&_Database_serviceDesc, srv)
}

func _Database_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Database/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Database_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Database",
	HandlerType: (*DatabaseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Database_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/database.proto",
}

func init() { proto1.RegisterFile("proto/database.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x49, 0x2c, 0x49, 0x4c, 0x4a, 0x2c, 0x4e, 0xd5, 0x03, 0x73, 0x85, 0x58, 0xc1,
	0x94, 0x52, 0x33, 0x23, 0x17, 0x47, 0x50, 0x6a, 0x71, 0x7e, 0x69, 0x51, 0x72, 0xaa, 0x90, 0x10,
	0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0x2d, 0xa4,
	0xc1, 0xc5, 0x92, 0x9d, 0x99, 0x97, 0x22, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x67, 0x24, 0x02, 0xd1,
	0xad, 0x07, 0xd3, 0xa2, 0xe7, 0x9d, 0x99, 0x97, 0x12, 0x04, 0x56, 0xa1, 0x64, 0xc9, 0xc5, 0x02,
	0xe2, 0x09, 0x71, 0x73, 0xb1, 0x87, 0xfa, 0x79, 0xfb, 0xf9, 0x87, 0xfb, 0x09, 0x30, 0x08, 0x71,
	0x72, 0xb1, 0x86, 0x38, 0x3a, 0xf9, 0xb8, 0x0a, 0x30, 0x0a, 0x71, 0x70, 0xb1, 0x84, 0x79, 0xba,
	0x86, 0x0b, 0x30, 0x09, 0xf1, 0x73, 0x71, 0x07, 0x87, 0xf8, 0x07, 0xb9, 0xba, 0xc4, 0x07, 0x04,
	0xf9, 0x3b, 0x0b, 0x30, 0x2b, 0xf1, 0x72, 0x71, 0xfb, 0x64, 0x16, 0x97, 0x04, 0xa5, 0x16, 0x96,
	0xa6, 0x16, 0x97, 0x28, 0xd9, 0x72, 0xf1, 0x40, 0xb8, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42,
	0xba, 0x5c, 0x9c, 0x45, 0x50, 0x0b, 0x8b, 0x25, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0xf8, 0xd1,
	0x1c, 0x12, 0x84, 0x50, 0x61, 0x64, 0xcd, 0xc5, 0xe1, 0x02, 0xf5, 0xac, 0x90, 0x3e, 0x17, 0x0b,
	0xc8, 0x28, 0x21, 0x21, 0xa8, 0x7a, 0x24, 0x6b, 0xa4, 0x84, 0x51, 0xc4, 0x20, 0x76, 0x25, 0xb1,
	0x81, 0xc5, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x05, 0x6c, 0x7d, 0x6b, 0x36, 0x01, 0x00,
	0x00,
}
